spring:
  couchbase:
    connection-string: localhost
    username: products
    password: products
    bucket: products
    env:
      timeouts:
        connect: 60000
        query: 60000
      ssl:
        enabled: false
services:
  couchbase:
    event:
      connectionString: localhost
      username: events
      password: events
      bucket: events
      env:
        timeouts:
          connect: 60000
          query: 60000
        ssl:
          enabled: false
