FROM adoptopenjdk/openjdk11

RUN apt-get update && \
    apt-get install -y unzip && \
    apt-get clean;
COPY entrypoint.sh /
ADD https://mirrors.estointernet.in/apache/kafka/3.0.0/kafka_2.12-3.0.0.tgz /
ADD https://packages.couchbase.com/clients/kafka/4.1.2/couchbase-kafka-connect-couchbase-4.1.2.zip /
RUN tar -xzf kafka_2.12-3.0.0.tgz
RUN unzip couchbase-kafka-connect-couchbase-4.1.2.zip

ENV KAFKA_HOME /kafka_2.12-3.0.0
RUN export KAFKA_HOME
ENV COUCHBASE_CONNECT_HOME /couchbase-kafka-connect-couchbase-4.1.2
RUN export COUCHBASE_CONNECT_HOME
ENV CLASSPATH /couchbase-kafka-connect-couchbase-4.1.2/lib/*
RUN export CLASSPATH

WORKDIR $COUCHBASE_CONNECT_HOME

CMD ["sh","/entrypoint.sh"]



