version: '3'
services:
  couchbase:
    build:
      context: .
    #container_name: couchbase1
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"
    environment:
      CLUSTER_USERNAME: Administrator
      CLUSTER_PASSWORD: admin12345
      CLUSTER_NAME: My Couchbase Node
      SERVICES: data,index,query,fts
      CLUSTER_RAMSIZE: 500
      BUCKET: product
      BUCKET_RAMSIZE: 100
      NODE_INIT_INDEX_PATH: /opt/couchbase/var/lib/couchbase/indexes
      RBAC_USERNAME: product
      RBAC_PASSWORD: product
      RBAC_ROLES: bucket_full_access[product]
