version: '3'
services:
  couchbase-6.5.1:
    build:
      context: .
    #container_name: couchbase1
    ports:
      - "8091-8094:8091-8094"
      - "11210:11210"
    environment:
      CLUSTER_USERNAME: Administrator
      CLUSTER_PASSWORD: admin12345
      CLUSTER_NAME: My Couchbase Node
      SERVICES: data,index,query,fts
      CLUSTER_RAMSIZE: 1024
      BUCKET: products
      BUCKET_1: events
      BUCKET_RAMSIZE: 100
      NODE_INIT_INDEX_PATH: /opt/couchbase/var/lib/couchbase/indexes
      RBAC_USERNAME: products
      RBAC_USERNAME_1: events
      RBAC_PASSWORD: products
      RBAC_PASSWORD_1: events
      RBAC_ROLES: bucket_full_access[products]
      RBAC_ROLES_1: bucket_full_access[events]
